version: '3'
services:
  Eureka:
    image: 'alexandersupertramp/serviceregistry:latest'
    container_name: Eureka
    ports:
      - '8761:8761'
  configserver:
    image: 'alexandersupertramp/configserver:latest'
    container_name: configserver
    ports:
      - '9296:9296'
    environment:
      - EUREKA_SERVER_URL=http://Eureka:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://configserver:9296/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - Eureka
  cloudgateway:
    image: 'alexandersupertramp/cloudgateway:latest'
    container_name: cloudgateway
    ports:
      - '9090:9090'
    environment:
      - EUREKA_SERVER_URL=http://Eureka:8761/eureka
      - CONFIG_SERVER_URL=http://configserver:9296
    depends_on:
      configserver:
        condition: service_healthy

  productservice:
    image: 'alexandersupertramp/productservice:latest'
    container_name: productservice
    ports:
      - '8080:8080'
    environment:
      - EUREKA_SERVER_URL=http://Eureka:8761/eureka
      - CONFIG_SERVER_URL=http://configserver:9296
    depends_on:
      configserver:
        condition: service_healthy

  paymentservice:
    image: 'alexandersupertramp/paymentservice:latest'
    container_name: paymentservice
    ports:
      - '8081:8081'
    environment:
      - EUREKA_SERVER_URL=http://Eureka:8761/eureka
      - CONFIG_SERVER_URL=http://configserver:9296
    depends_on:
      configserver:
        condition: service_healthy

  orderservice:
    image: 'alexandersupertramp/orderservice:latest'
    container_name: orderservice
    ports:
      - '8082:8082'
    environment:
      - EUREKA_SERVER_URL=http://Eureka:8761/eureka
      - CONFIG_SERVER_URL=http://configserver:9296
    depends_on:
      configserver:
        condition: service_healthy